selenium:
  image: selenium/standalone-firefox-debug
  ports:
    - "4444:4444"
    - "5900:5900"
  links:
    - dienes

dienes:
  image: smebberson/alpine-nginx
  volumes:
    - ./dist:/usr/html

ete:
  build: ./ete
  volumes:
    - ./screenshots:/screenshots
  links:
    - selenium
  command: npm run nightwatch
